### ISSUE TITLE
Compiliation error with static binary library files (PIE object issues)

### ISSUE THREAD

**Issue by lucajovine** [czimaginginstitute/GCtfFind#5]
This seems to have the same issue as MotionCor3:

[https://github.com/czimaginginstitute/MotionCor3/issues/4](https://github.com/czimaginginstitute/MotionCor3/issues/4)

...

**Comment by jonathanrd** [comment]
The following edit to the makefile, similar to the MotionCor3 fix, seems to work:
```
exe: $(OBJS)
        @g++ -g -pthread -m64 $(OBJS) \
        $(PRJLIB)/libmrcfile.a \
        $(PRJLIB)/libutil.a \
        $(PRJLIB)/libcuutil.a \
        $(PRJLIB)/libcuutilfft.a \
        -L$(CUDALIB) -L/usr/lib64 \
        -lcufft -lcudart -lcuda -lc -lm -lpthread \
        -no-pie \
        -o GCtfFind
        @echo GCtfFind has been generated.
```

**Comment by lucajovine** [comment]
> The following edit to the makefile, similar to the MotionCor3 fix, seems to work:
> 
> ```
> exe: $(OBJS)
>         @g++ -g -pthread -m64 $(OBJS) \
>         $(PRJLIB)/libmrcfile.a \
>         $(PRJLIB)/libutil.a \
>         $(PRJLIB)/libcuutil.a \
>         $(PRJLIB)/libcuutilfft.a \
>         -L$(CUDALIB) -L/usr/lib64 \
>         -lcufft -lcudart -lcuda -lc -lm -lpthread \
>         -no-pie \
>         -o GCtfFind
>         @echo GCtfFind has been generated.
> ```

Thanks, this indeed works for me as well!

**Comment by lucajovine** [comment]
PS: does not work with MotionCor3, though...
